---
title: "612415196 Warfade Krishna Vijay's Assignment 2"
output:
  word_document: default
  html_document: default
---
Q1.Create a dataframe containing Employee Name, Department, DA and TA with the record of 8 employees.
```{r}
Table <- data.frame(Employee_Name = c("Ravi", "Raju", "Arnav",
                                      "Prasad","Robert", "Ishan",
                                      "Patrick", "Rohan"),
                    Department = c("Maths", "Physics", "Chemistry",
                                   "Water", "Food", "Coding",
                                   "Cleanliness", "Security"),
                    Salary = c(1000,2000, 3000, 4000, 5000, 6000, 7000,
                               8000),
                    DA = c(23, 43, 65, 58, 96, 30, 75, 44),
                    TA = c(2, 1, 4, 5, 6, 3, 2, 7))
View(Table)
knitr::kable(Table)
```
Q2.Add 2 rows to the existing table and find the dimension of new table.
```{r}
New_Table <- rbind(Table, c("Atharva", "Computer", 8700, 56, 9),
                          c("Aryan", "OS", 6800, 46, 8))
View(New_Table)
dim(New_Table)
knitr::kable(New_Table)
```